### ISSUE TITLE
Time Zone update not working

### ISSUE THREAD

**Issue by iAmSaugata** [modem7/DHCP-Relay#19]
Hi,
I with this image time zone update not working with EV or host folder mapping. Could you please check.

**Comment by modem7** [comment]
What's your docker compose look like?

**Comment by iAmSaugata** [comment]
Fixed by mapping host time zone file.

**Comment by iAmSaugata** [comment]
I will do the test.

**Comment by iAmSaugata** [comment]
Time Zone working with this build.

**Comment by modem7** [comment]
Updated in https://github.com/modem7/DHCP-Relay/commit/18982ddbba2881e95c7daa3d6a33558d8e8cbf5b
